commerce_ibis.commerce_payment_gateway.plugin.worldline_redirect_checkout:
  type: commerce_payment_gateway_configuration
  mapping:
    merchant_id:
      type: string
      label: 'Merchant ID.'
    cert_pass:
      type: string
      label: 'Passkey from Merchant.'
    cert_location:
      type: string
      label: 'Currently active Certificate location.'
    ecomm_client_url:
      type: string
      label: 'Url base to redirect clients to for payment.'
    ecomm_server_url:
      type: string
      label: 'Url used in order to connect to IBIS provider.'
