<?php

// use Drupal\commerce_ibis\Merchant\Merchant;
// use Drupal\Core\Database\Database;

/**
 * Perform closeDay() for batch payments.
 */
function commerce_ibis_cron() {
  // Last time we closed day.
  // if (\Drupal::state()->get('commerce_ibis.IBIS_lastclosedate')
  //   != format_date(REQUEST_TIME, 'custom', 'Ymd')) {
  //   // Retrieve IBIS config information for connection.
  // $settings =
  // \Drupal::config('commerce_payment.commerce_payment_gateway.worldline_creditcard_payment');
  //   $configuration = $settings->getRawData()['configuration'];

  //   $ecomm_server_url = $configuration['ecomm_server_url'];
  //   $cert_url = $configuration['cert_location'];
  //   // Real directory path to cert file.
  //   $real_cert_path = \Drupal::service('file_system')->realpath($cert_url);
  //   $cert_pass = $configuration['cert_pass'];

  //   $merchant = new Merchant($ecomm_server_url, $real_cert_path, $cert_pass, 1);
  //   $resp = $merchant->closeDay();

  //   $date_now = format_date(REQUEST_TIME, 'custom', 'Ymd');

  //   $log_msg = t('Commerce_ibis day has been closed at @date', ['@date' => $date_now]);
  //   \Drupal::logger('commerce_ibis')->notice($log_msg);
  //   \Drupal::state()->set('commerce_ibis.IBIS_lastclosedate', $date_now);

  //   $connection = Database::getConnection();
  //   // RESULT: OK RESULT_CODE: 500 FLD_075: 4 FLD_076: 6 FLD_087: 40.
  //   // FLD_088: 60.
  //   if (strstr($resp, 'RESULT:')) {
  //     $result = explode('RESULT: ', $resp);
  //     $result = preg_split('/\r\n|\r|\n/', $result[1]);
  //     $result = $result[0];
  //   }
  //   else {
  //     $result = '';
  //   }

  //   if (strstr($resp, 'RESULT_CODE:')) {
  //     $result_code = explode('RESULT_CODE: ', $resp);
  //     $result_code = preg_split('/\r\n|\r|\n/', $result_code[1]);
  //     $result_code = $result_code[0];
  //   }
  //   else {
  //     $result_code = '';
  //   }

  //   if (strstr($resp, 'FLD_075:')) {
  //     $count_reversal = explode('FLD_075: ', $resp);
  //     $count_reversal = preg_split('/\r\n|\r|\n/', $count_reversal[1]);
  //     $count_reversal = $count_reversal[0];
  //   }
  //   else {
  //     $count_reversal = '';
  //   }

  //   if (strstr($resp, 'FLD_076:')) {
  //     $count_transaction = explode('FLD_076: ', $resp);
  //     $count_transaction = preg_split('/\r\n|\r|\n/', $count_transaction[1]);
  //     $count_transaction = $count_transaction[0];
  //   }
  //   else {
  //     $count_transaction = '';
  //   }

  //   if (strstr($resp, 'FLD_087:')) {
  //     $amount_reversal = explode('FLD_087: ', $resp);
  //     $amount_reversal = preg_split('/\r\n|\r|\n/', $amount_reversal[1]);
  //     $amount_reversal = $amount_reversal[0];
  //   }
  //   else {
  //     $amount_reversal = '';
  //   }

  //   if (strstr($resp, 'FLD_088:')) {
  //     $amount_transaction = explode('FLD_088: ', $resp);
  //     $amount_transaction = preg_split('/\r\n|\r|\n/', $amount_transaction[1]);
  //     $amount_transaction = $amount_transaction[0];
  //   }
  //   else {
  //     $amount_transaction = '';
  //   }

  //   $now = format_date(REQUEST_TIME, 'custom', 'Y-m-d H:i:s');
  //   $result = $connection->insert('commerce_ibis_batch')
  //     ->fields([
  //       'result' => $result,
  //       'result_code' => $result_code,
  //       'count_reversal' => $count_reversal,
  //       'count_transaction' => $count_transaction,
  //       'amount_reversal' => $amount_reversal,
  //       'amount_transaction' => $amount_transaction,
  //       'close_date' => $now,
  //       'response' => $resp
  //     ])
  //     ->execute();
  // }

}
